README.md
Adding ZeroDev, and also fix & add references to Infinitism.
=> Add ZeroDev and also fix references to Infinitism

CONTRIBUTING.md
Signed-off-by: TomTaehoonKim <kim.taehoon@snu.ac.kr>
This PR fixes the broken url for "How to Contribute to an Open Source Project on GitHub".
=> Fix broken url

README.md
https://twitter.com/camiinthisthang/status/1617563360328908800?s=46&t=dWHocvd9_KIqEaXgKuZlZQ
=> Add new AA guide by @camiinthisthang

README.md
Comparing those two is an  incredibly important topic when it comes to account abstraction. AA is an effort to enable SCWs, and MPC wallets are an adjacent technology but commonly compared to SCWs. 
Furthermore, AA efforts aim to solve some of the cons that SCWs previously had, which makes the argument in favor of SCW+AA over MPC even stronger.
=> Adding MPC vs SCW comparison thread

README.md
Add https://safe.mirror.xyz/9KmZjEbFkmI79s28d9xar6JWYrE50F5AHpa5CR12YGI to reading materials (Current Landscape)
=> Add Safe AA Article to Current Landscape

README.md
Added Etherspot's bundler implementation
=> Added Etherspot's bundler implementation

README.md
=> resolve backlogs #33 #23 #20 #17 #16

README.md
Added RPC providers list from (#32)
Added Dune dashboards from (#38)
Added Newsletters section
Closes #32 #38
=> Add RPC Providers list, Dune dashboards and newsletters sections

README.md
We've changed our SDK repo and open-sourced our wallet implementation.
=> ZeroDev-related updates

README.md
See this for more context: https://twitter.com/zerodev_app/status/1636465069688229889
=> Link to ERC-6492 and related articles

README.md
Add UserOperation Indexer code
=> Add UserOperation Indexer

README.md
Related tweet thread: https://twitter.com/zerodev_app/status/1653417815117004802
=> Add article about session keys

README.md
Add Bundler P2P network twitter thread by Partha
=> Add Bundler P2P network twitter thread

README.md
The current Infinitism URL leads to a 404 page.
=> [Fix] Update README with new Infinitism EIP 4337 website

README.md
- Quick update to the README: Ethereum Improvement ~Processes~ Proposals
=> docs: fix incorrect long form of EIP

README.md
Add "Understanding Account Abstraction" by Alchemy to the list
=> Add "Understanding Account Abstraction" 

README.md
Add a P256 lib that can verify sigs with 1/3rd the gas
=> Add FreshCryptoLib, efficient P256 implementation

README.md
Added decoded page for AA 
https://blocktheory.com/decoded/account-abstraction-use-cases/
=>  Add Blocktheory, Account Abstraction Decoded to Everyday Normies

README.md
Add link for Transeptor bundler.
=> feat: add transeptor bundler

README.md
DeCommas provides developer-friendly API to access indexed on-chain data including **UserOperations history** and detailed **UserOperation info by hash** for 15+ networks.
Basic info and supported networks: https://build.decommas.io
API docs: https://docs.decommas.io
=> Add DeCommas API Explorer Project

README.md
- Adding resources to intro, blog, video, and EIP
- Sorting lists alphabetically
=> Adding resources and sorting lists alphabetically 

README.md
Hey folks!
I have added Aarc in the SDK and project section of the docs. Aarc is working towards building an onboarding kit over AA. We already have the aarc-sdk live, allowing users to migrate funds from EOAs to Smart contract wallets gasless. We are developing interesting new products that will make the onboarding experience much smoother and more efficient for the users.
=> Add Aarc project

README.md
Hi 👋
- Prompted by Eric's telegram message https://t.me/c/1863441549/17732
- Not sure if 'Current Landscape / Thoughts / Threads' is the right category
- I feel a bit cheeky inserting at the top but I'm not sure what determines the order and most-recent-first seems plausible :)
=> Add wax compression article

README.md
Added thirdweb links to the following sections
- SDK and libraries
- Smart contracts
- Projects using Account Abstraction
=> Add thirdweb

README.md
- Updated Etherspot SDK, Contract to Prime version
- Added Arka Paymaster (open source solution)
- Added twitter thread about bundler implementations
=> Update Etherspot SDK, Contracts and Paymaster

README.md
@porco-rosso-j has a better repo to use as an example, which builds on the one listed and is better documented.
=> Update code link in README.md

README.md
Fixes link checker reports #249
=> Fix twitter thread link and permissionless

README.md
[Shakespay](https://shakesco.netlify.app/) - Shakespay is an erc4337 compliant wallet, built by shakesco, to enable the growth of Ethereum ecosystem. The app has basic financial services ranging from sending, receiving to requesting. The real power of ERC4337 is seen in the technologies we have built. You can now perform automated payments that [visa](https://usa.visa.com/solutions/crypto/rethink-digital-transactions-with-account-abstraction.html) proved was possible through shakespay, you can perform private transactions through stealth addresses, transaction batching, social login, business can deploy their own collectibles and tokens and offer them as loyalty tokens to shakespay users, own you web3 identity through demand-based recurring fee name system and much more. We have also …
=> add shakespay

.github/workflows/virustotal-linkchecker.yml
Implemented VirusTotal - Malicious URL checker idea by @randomishwalk as discussed #187 
p.s malicious/suspicious threshold is set to 1 to prevent false positive reports for some urls.
=> Implement VirusTotal - Malicious Link Checker GitHub action

README.md
Hey! This PR adds [Picnic](https://usepicnic.com/) to the Projects section. 
Picnic is a DeFi consumer app that uses ERC4337 to deliver a user experience as simple as fintech. It is currently focused in the Brazilian market and doing 20k usersOps with 6M USD in volume per month. 
Happy to answer any questions. Thanks!
=> Adding Picnic to project list
